ACTION_VIEW_GRAPH = 100
ACTION_VIEW_RANKING = 200
ACTION_VIEW_PROGRESS = 300
ACTION_VIEW_REPORTS = 400
ACTION_VIEW_DISPLAY = 500
ACTION_VIEW_ALERT = 600
ACTION_VIEW_PRINTER = 700

AUDIT_ACTIONS = {
    ACTION_VIEW_GRAPH: 'View graph',
    ACTION_VIEW_RANKING: 'View ranking',
    ACTION_VIEW_PROGRESS: 'View progress',
    ACTION_VIEW_REPORTS: 'View reports',
    ACTION_VIEW_DISPLAY: 'View display',
    ACTION_VIEW_ALERT: 'View alert',
    ACTION_VIEW_PRINTER: 'View printer',
}
