postgres:
  image: postgres:9.4
  environment:
      POSTGRES_PASSWORD: postgres

mongo:
  image: mongo:2.6.5

rabbitmq:
  image: rabbitmq:3.5.0

uwsgi:
  build: dockers/uwsgi
  command: uwsgi --ini dockers/uwsgi/uwsgi.ini
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

webserver:
  build: dockers/nginx
  command: [nginx, -g, "daemon off;"]
  volumes:
    - .:/srv
  links:
    - uwsgi
  ports:
    - "80:80"
    - "443:443"

celerybase:
  build: dockers/celery
  command: /bin/bash

cwcelery:
  image: entrakdms_celerybase
  command: python -m celery worker --app=entrak --loglevel=INFO -Q celery
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

cwtaskstarter:
  image: entrakdms_celerybase
  command: python -m celery worker --app=entrak --loglevel=INFO -Q task_starter
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

cwrecap:
  image: entrakdms_celerybase
  command: python -m celery worker --app=entrak --loglevel=INFO -Q recap
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

cwrecover:
  image: entrakdms_celerybase
  command: python -m celery worker --app=entrak --loglevel=INFO -Q recover
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

celerybeat:
  image: entrakdms_celerybase
  command: celery beat --app=entrak
  volumes:
    - .:/srv
  links:
    - postgres
    - mongo
    - rabbitmq

