# -*- encoding: utf-8 -*-
DECIMAL_SEPARATOR = '.'
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3
DATE_FORMAT = u'Y年 n月 d日'
YEAR_MONTH_FORMAT = u'Y年 n月'
MONTH_DAY_FORMAT = u'n月 d日'
SHORT_MONTH_FORMAT = u'n月'
YEAR_FORMAT = u'Y年'
